config/routes.rb
Rails.application.routes.draw do
  get '/page-2', to: 'page2#index', as: 'page2'
  root 'home#index'
  match "/delayed_job" => DelayedJobWeb, :anchor => false, :via => [:get, :post]
  mount RedisBrowser::Web => '/redis-browser'

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords'
  }

  resources :teachers, only: [:index, :show]
  resources :students, only: [:index, :show]
  resources :profile, only: :none do
    collection do
      post :toggle_activate
      post :toggle_activate_student
    end
  end

  namespace :api do
    namespace :v1 do

      resources :users, only: [:show] do
        collection do
          post :signin
          post :signup
          get  :address, to: 'users#address'
          post :forgot_password
          post :resetpassword
          post :update_password
          get  'profile/:id', to: 'users#profile'
        end
      end

      resources :teacher_profiles, only: [:show, :update] do
        collection do
          post :interests
          get :interests
          post :languages
          get :languages
          get :students
          get :suspended_students
          get :unsuspended_students
          get :my_community
          post 'toggle_activate_student/:student_id', to: 'teacher_profiles#toggle_activate_student'
        end
      end

      resources :students, only: [:create, :update] do
        collection do
          post  :interests
          get   :interests
          post  :languages
          get   :languages
          get   :my_community
        end
      end

    end
  end

end

app/controllers/api/v1/students_controller.rb
require "google/cloud/firestore"

class Api::V1::StudentsController < Api::V1::ApiController
  before_action :authenticate_via_token
  before_action :only_students, only: [:my_community]

  def create
    return render json: { success: false, msg: 'Email is required.' } if params[:student][:email].blank?
    begin
      password = Devise.friendly_token.first(6)
      @student = User.create!(email: params[:student][:email].downcase, password: password)
      @student.add_role(:student)

      @student.create_profile(student_params, {teacher_id: @user.id})

      # Adding user_status on firebase w.r.t user id
      firestore = Google::Cloud::Firestore.new credentials: ENV["FIREBASE_CREDENTIALS_PATH"]
      doc_ref = firestore.doc("user_status/#{@student.id}")
      doc_ref.set(is_active: true)

      ## Notify student about their login
      StudentsMailer.new_account(@student, password).deliver_now
    rescue Exception => e
      return render json: { success: false, msg: e.message }
    end
  end

  ## Students community
  def my_community
    # teacher_id = @user.student_profile.teacher_id
    @students = StudentProfile.all
    @students = @students.select{ |student| !student.about.nil?}
    @class_fellows = @user.profile.class_fellows
  end

  def update
    @profile = @user.profile
    @profile.update_attributes(student_params)
    Picture.find_or_initialize_by(imageable_id: @profile.id, imageable_type: "StudentProfile").update_attributes(avatar_params)
  end

  def interests
    if request.get?
      @interests = @user.interests
      msg = 'User interests'
    end

    if request.post?
      @user.interest_list = params[:interests]
      @user.save

      @interests = @user.interests
      msg = 'Interests saved.'
    end

    return render json: {success: true, msg: msg, data: {interests: @interests.join(",")} }
  end

  def languages
    if request.post?
      @user.languages.destroy_all
      params[:languages].each do |lang|
        UserLanguage.create!(user_id: @user.id, language_code: lang[:language_code], is_native: lang[:is_native]) rescue ActiveRecord::RecordNotUnique
      end
    end

    @languages = @user.languages.reload
  end

  private
    def student_params
      params.fetch(:student, {}).permit(:name, :grade, :school, :age, :avatar, :about)
    end

    def only_students
      return render json: { success: false, msg: 'Data only for students.' } unless @user.has_role?(:student)
    end

    def avatar_params
      params.fetch(:avatar, {}).permit(:avatar_hair, :avatar_accessories, :avatar_facial_hair, :avatar_facial_hair_color, :avatar_clothes, :avatar_skin_color)
    end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_student, only: [:show]

  def index
    ## Paginate the end result
    apply_filters()
    ## Paginate the end result
    @students = Kaminari.paginate_array(@students).page(params[:page])
    @student  = @students.first
    # @total_count = @students.size
  end

  def show
  end

  private
    def set_student
      @student = User.find_by(id: params[:id])
    end

    def apply_filters
      @students = User.with_role(:student)

      # Filter For School
      if !params[:school].blank?
        @students = @students.select{ |student| student.profile.school== params[:school]}
      end

      ## Status filter
      unless params[:status].blank? or params[:status] == 'Any'
        params[:status] == "true" ? @students = @students.select{|student| student.is_active?} : @students = @students.select{|student| !student.is_active?}
      end

      ## Age filter
      unless params[:age].blank?
        @students = @students.select{ |student| student.profile.age == params[:age].to_i}
      end

      ## Grade filter
      unless params[:grade].blank?
        @students = @students.select{ |student| student.profile.grade == params[:grade].to_i}
      end

      ## Language Filter
      unless params[:lang].blank?
        lang = params[:lang]
        @students = @students.select{|student| student.languages.map{|l| l.language_code}.include?(lang)}
      end
      unless params[:lang_status].blank?
        status_check = (params[:lang_status].to_s.downcase == "true")
        @students = @students.select{|student| student.languages.select{ |l| l.is_native.eql?(status_check) && (!params[:lang].blank? ? l.language_code.eql?(params[:lang]) : true)}.any?}

      end
    end

end

app/helpers/api/v1/students_helper.rb
module Api::V1::StudentsHelper
end

app/views/students/_filters.slim
/! Filters
.ui-bordered.px-4.pt-4.mb-4
  / params.merge(:action=>"index")
  = form_tag students_path(), method: :get do
    .form-row
      .col-md.mb-4
        label.form-label School
        = text_field_tag :school, params[:school], class: 'form-control', placeholder: "School name"

      .col-md.mb-4
        label.form-label Account Status
        = select_tag :status, options_for_select([['Approved', true], ['Not Approved', false]], selected: params[:status]), class: 'custom-select', prompt: 'Any'

      .col-md.mb-4
        label.form-label Age
        = select_tag :age, options_for_select((5..20).step(1).map{|s| ["#{s}", s]}, selected: params[:age]), class: 'custom-select', prompt: 'Any'

      .col-md.mb-4
        label.form-label Grade
        = select_tag :grade, options_for_select((1..12).step(1).map{|s| ["#{s}", s]}, selected: params[:grade]), class: 'custom-select', prompt: 'Any'

      .col-md.mb-4
        label.form-label Language
        = select_tag :lang, options_from_collection_for_select(LanguageList::COMMON_LANGUAGES, "iso_639_1", "name", selected: params[:lang]), class: 'custom-select', prompt: 'Any'

      .col-md.mb-4
        label.form-label Language Status
        = select_tag :lang_status, options_for_select([['Native', true], ['Learned', false]], selected: params[:lang_status]), class: 'custom-select', prompt: 'Any'

      .col-md.col-xl-2.mb-4
        label.form-label.d-none.d-md-block &nbsp;
        = submit_tag 'Apply', class: 'btn btn-danger btn-block'
/! / Filters

app/views/students/index.slim
- content_for :styles do
  = stylesheet_link_tag 'datatables/datatables.css', media: 'all'
  = stylesheet_link_tag 'ladda/ladda.css', media: 'all'

- content_for :scripts do
  = javascript_include_tag 'spin/spin.js'
  = javascript_include_tag 'ladda/ladda.js'

h4.d-flex.justify-content-between.align-items-center
  span.text-muted.font-weight-light Students

hr.border-light.container-m--x.mt-0.mb-4/
= render partial: 'filters'

.card
  .card-header
    - if @students.any?
      .card-datatable.table-responsive
        #DataTables_Table_1_wrapper.dataTables_wrapper.dt-bootstrap4.no-footer
          .row
            .col-sm-12
              table#DataTables_Table_1.datatables-demo.table.table-striped.table-bordered.dataTable.no-footer aria-describedby="DataTables_Table_1_info" role="grid"
                thead
                  tr role="row"
                    th ID
                    th Name
                    th Email
                    th School
                    th Age
                    th Grade
                    th Approve
                tbody
                  - @students.each_with_index do |student, index|
                    tr
                      td
                        = student.id
                      td
                        = student.profile.name
                      td
                        = student.email
                      td
                        = student.profile.school
                      td
                        = student.profile.age
                      td
                        = student.profile.grade
                      td
                        = link_to student.is_active ? 'Deactivate' : 'Activate', toggle_activate_student_profile_index_path(id: student.id), data: {:confirm=>'Are you really want to proceed?'},  remote: true, method: :post, class: "btn #{student.is_active ? 'btn-danger' : 'btn-success'} btn-sm lnk-activate", id: "lnk-activate-#{student.id}"

          .row
            .col-sm-12.col-md-5
            .col-sm-12.col-md-7
              #DataTables_Table_1_paginate.dataTables_paginate.paging_simple_numbers
                = paginate @students