config/routes.rb
Rails.application.routes.draw do
  get '/page-2', to: 'page2#index', as: 'page2'
  root 'home#index'
  match "/delayed_job" => DelayedJobWeb, :anchor => false, :via => [:get, :post]
  mount RedisBrowser::Web => '/redis-browser'

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords'
  }

  resources :teachers, only: [:index, :show]
  resources :students, only: [:index, :show]
  resources :profile, only: :none do
    collection do
      post :toggle_activate
      post :toggle_activate_student
    end
  end

  namespace :api do
    namespace :v1 do

      resources :users, only: [:show] do
        collection do
          post :signin
          post :signup
          get  :address, to: 'users#address'
          post :forgot_password
          post :resetpassword
          post :update_password
          get  'profile/:id', to: 'users#profile'
        end
      end

      resources :teacher_profiles, only: [:show, :update] do
        collection do
          post :interests
          get :interests
          post :languages
          get :languages
          get :students
          get :suspended_students
          get :unsuspended_students
          get :my_community
          post 'toggle_activate_student/:student_id', to: 'teacher_profiles#toggle_activate_student'
        end
      end

      resources :students, only: [:create, :update] do
        collection do
          post  :interests
          get   :interests
          post  :languages
          get   :languages
          get   :my_community
        end
      end

    end
  end

end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_teacher, only: [:show]

  def index
    ## Paginate the end result
    apply_filters()
    ## Paginate the end result
    @teachers = Kaminari.paginate_array(@teachers).page(params[:page])
    @teacher  = @teachers.first
    # @total_count = @teachers.size
  end

  def show
  end

  private
    def set_teacher
      @teacher = User.find_by(id: params[:id])
    end

    def apply_filters
      @teachers = User.with_any_role(:teacher)

      # Filter For School
      if !params[:organization].blank?
        @teachers = @teachers.select{ |teacher| teacher.profile.organization == params[:organization]}
      end

      ## Status filter
      unless params[:status].blank? or params[:status] == 'Any'
        params[:status] == "true" ? @teachers = @teachers.select{|teacher| teacher.is_active?} : @teachers = @teachers.select{|teacher| !teacher.is_active?}
      end

      ## Language Filter
      unless params[:lang].blank?
        lang = params[:lang]
        @teachers = @teachers.select{|teacher| teacher.languages.map{|l| l.language_code}.include?(lang)}
      end

      unless params[:lang_status].blank?
        status_check = (params[:lang_status].to_s.downcase == "true")
        @teachers = @teachers.select{|teacher| teacher.languages.select{ |l| l.is_native.eql?(status_check) && (!params[:lang].blank? ? l.language_code.eql?(params[:lang]) : true)}.any?}
      end
    end

end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/teachers/_filters.slim
/! Filters
.ui-bordered.px-4.pt-4.mb-4
  / params.merge(:action=>"index")
  = form_tag teachers_path(), method: :get do
    .form-row
      .col-md.mb-4
        label.form-label Organization
        = text_field_tag :organization, params[:organization], class: 'form-control', placeholder: "Organization name"

      .col-md.mb-4
        label.form-label Account Status
        = select_tag :status, options_for_select([['Approved', true], ['Not Approved', false]], selected: params[:status]), class: 'custom-select', prompt: 'Any'

      .col-md.mb-4
        label.form-label Language
        = select_tag :lang, options_from_collection_for_select(LanguageList::COMMON_LANGUAGES, "iso_639_1", "name", selected: params[:lang]), class: 'custom-select', prompt: 'Any'

      .col-md.mb-4
        label.form-label Language Status
        = select_tag :lang_status, options_for_select([['Native', true], ['Learned', false]], selected: params[:lang_status]), class: 'custom-select', prompt: 'Any'


      .col-md.col-xl-2.mb-4
        label.form-label.d-none.d-md-block &nbsp;
        = submit_tag 'Apply', class: 'btn btn-danger btn-block'
/! / Filters

app/views/teachers/index.slim
- content_for :styles do
  = stylesheet_link_tag 'datatables/datatables.css', media: 'all'
  = stylesheet_link_tag 'ladda/ladda.css', media: 'all'

- content_for :scripts do
  = javascript_include_tag 'spin/spin.js'
  = javascript_include_tag 'ladda/ladda.js'

h4.d-flex.justify-content-between.align-items-center
  span.text-muted.font-weight-light Teachers

hr.border-light.container-m--x.mt-0.mb-4/
= render partial: 'filters'

.card
  .card-header
    - if @teachers.any?
      .card-datatable.table-responsive
        #DataTables_Table_1_wrapper.dataTables_wrapper.dt-bootstrap4.no-footer
          .row
            .col-sm-12
              table#DataTables_Table_1.datatables-demo.table.table-striped.table-bordered.dataTable.no-footer aria-describedby="DataTables_Table_1_info" role="grid"
                thead
                  tr role="row"
                    th ID
                    th Name
                    th Email
                    th Organization
                    th Phone
                    th Approve
                tbody
                  - @teachers.each_with_index do |teacher, index|
                    tr
                      td
                        = teacher.id
                      td
                        = teacher.profile.try(:full_name)
                      td
                        = teacher.email
                      td
                        = teacher.profile.try(:organization)
                      td
                        = teacher.profile.try(:phone)
                      td
                        = link_to teacher.is_active ? 'Deactivate' : 'Activate', toggle_activate_profile_index_path(id: teacher.id), remote: true, method: :post, class: "btn #{teacher.is_active ? 'btn-danger' : 'btn-success'} btn-sm lnk-activate", id: "lnk-activate-#{teacher.id}", data: {:confirm=>'Are you really want to proceed?'}

          .row
            .col-sm-12.col-md-5
            .col-sm-12.col-md-7
              #DataTables_Table_1_paginate.dataTables_paginate.paging_simple_numbers
                = paginate @teachers

app/views/teachers/show.slim
h4.d-flex.justify-content-between.align-items-center
  span.text-muted.font-weight-light = 'Teacher Profile'

hr.border-light.container-m--x.mt-0.mb-4/

p#notice = notice

.card
  .card-body
    .card-title
      h5 = @teacher.teacher_profile.full_name
    strong Email: &nbsp;
    = @teacher.email
    br
    strong Contact: &nbsp;
    = @teacher.teacher_profile.phone

br

.detail-footer
  = link_to teachers_path(), class: 'btn btn-danger rounded-pill' do
    i.lnr.lnr-arrow-left
    | &nbsp; Back