config/routes.rb
Rails.application.routes.draw do
  get '/page-2', to: 'page2#index', as: 'page2'
  root 'home#index'
  match "/delayed_job" => DelayedJobWeb, :anchor => false, :via => [:get, :post]
  mount RedisBrowser::Web => '/redis-browser'

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords'
  }

  resources :teachers, only: [:index, :show]
  resources :students, only: [:index, :show]
  resources :profile, only: :none do
    collection do
      post :toggle_activate
      post :toggle_activate_student
    end
  end

  namespace :api do
    namespace :v1 do

      resources :users, only: [:show] do
        collection do
          post :signin
          post :signup
          get  :address, to: 'users#address'
          post :forgot_password
          post :resetpassword
          post :update_password
          get  'profile/:id', to: 'users#profile'
        end
      end

      resources :teacher_profiles, only: [:show, :update] do
        collection do
          post :interests
          get :interests
          post :languages
          get :languages
          get :students
          get :suspended_students
          get :unsuspended_students
          get :my_community
          post 'toggle_activate_student/:student_id', to: 'teacher_profiles#toggle_activate_student'
        end
      end

      resources :students, only: [:create, :update] do
        collection do
          post  :interests
          get   :interests
          post  :languages
          get   :languages
          get   :my_community
        end
      end

    end
  end

end

app/views/layouts/partials/_layout-footer.html.erb
<!-- Layout footer -->
<nav class="layout-footer footer bg-footer-theme">
  <div class="container-fluid container-p-x pb-3">    
    <a href="http://www.attribes.com" class="footer-link pt-3">Powered by <strong>Attribe Solutions</strong></a>
    
  </div>
</nav>
<!-- / Layout footer -->

app/views/layouts/partials/_layout-navbar.html.erb
<div id="sidenav-2" class="sidenav sidenav-horizontal bg-dark" style="position: relative;z-index: 100;border-top: 4px solid #d9534f;">
      <a href="#" class="sidenav-horizontal-prev disabled"></a><div class="sidenav-horizontal-wrapper"><ul class="sidenav-inner" style="margin-left: 0px;">
        <li class="sidenav-item">
          <a href="/" class="sidenav-link"><i class="sidenav-icon ion ion-ios-apps"></i>
            <div><%= Settings.brand_name %></div>
          </a>
        </li>

        <!--
        <li class="sidenav-item">
          <a href="javascript:void(0)" class="sidenav-link sidenav-toggle"><i class="sidenav-icon ion ion-ios-settings"></i>
            Item 1
          </a>
          <ul class="sidenav-menu">
            <li class="sidenav-item">
              <a href="javascript:void(0)" class="sidenav-link">
                <div>Item 1.1</div>
              </a>
            </li>
            <li class="sidenav-item">
              <a href="javascript:void(0)" class="sidenav-link">
                <div>Item 1.2</div>
              </a>
            </li>
            <li class="sidenav-item">
              <a href="javascript:void(0)" class="sidenav-link">
                <div>Item 1.3</div>
              </a>
            </li>
          </ul>
        </li>
        -->

        <% if user_signed_in? %>
          <li class="sidenav-item<%= current_page?(root_path) ? ' active' : '' %>">
            <%= link_to root_path, class: "sidenav-link" do %>
              <i class="sidenav-icon ion ion-ios-desktop"></i><div>Dashboard</div>
            <% end %>
          </li>
          <li class="sidenav-item">
            <a href="javascript:void(0)" class="sidenav-link sidenav-toggle"><i class="sidenav-icon ion ion-ios-contacts"></i>
                Members
              </a>
              <ul class="sidenav-menu">
                <li class="sidenav-item<%= controller_name == 'teachers' ? ' active' : '' %>">
                  <%= link_to teachers_path, class: "sidenav-link" do %>
                    <i class="sidenav-icon ion ion-md-contacts"></i><div>Teachers</div>
                  <% end %>
                </li>
                <li class="sidenav-item<%= controller_name == 'students' ? ' active' : '' %>">
                  <%= link_to students_path, class: "sidenav-link" do %>
                    <i class="sidenav-icon ion ion-md-hand"></i><div>Students</div>
                  <% end %>
                </li>
              </ul>
          </li>
          <li class="sidenav-item<%= controller_name == 'settings' ? ' active' : '' %>">
            <%= link_to root_path, class: "sidenav-link" do %>
              <i class="sidenav-icon ion ion-ios-cog"></i><div>Settings</div>
            <% end %>
          </li>


          <% if current_user.has_role?(:admin) %>
            <li class="sidenav-item<%= current_page?(agents_path) ? ' active' : '' %>">
              <%= link_to root_path, class: "sidenav-link" do %>
                <i class="sidenav-icon ion ion-ios-contact"></i><div>Agents</div>
              <% end %>
            </li>
          <% end %>

          <li class="sidenav-item">
            <%= link_to destroy_user_session_path, method: :delete, class: "sidenav-link" do %>
              <i class="sidenav-icon ion ion-md-exit"></i><div>Sign Out</div>
            <% end %>
          </li>

        <% end %>

      </ul>
    </div>
<a href="#" class="sidenav-horizontal-next disabled"></a></div>

<script>
  $(function() {
    new SideNav($('#sidenav-2')[0], {
      orientation: 'horizontal'
    });
  });
</script>

app/views/layouts/partials/_layout-sidenav.html.erb
<!-- Layout sidenav -->
<div id="layout-sidenav" class="<% if local_assigns[:horizontal] == true %>layout-sidenav-horizontal sidenav-horizontal container-p-x flex-grow-0<% else %>layout-sidenav sidenav-vertical<% end %> sidenav bg-danger">

  <!-- Inner -->
  <ul class="sidenav-inner<% if local_assigns[:horizontal] != true %> py-1<% end %>">
    <li class="sidenav-block my-1">
      <div class="media align-items-center">        
        <%= image_tag '1-small.png', class: 'd-block ui-w-50 rounded-circle' %>
        <div class="media-body pl-3">
          <h5 class="sidenav-text mb-1"><%= current_user.name %></h5>
          <div class="small">
            <a href="javascript:void(0)" class="sidenav-link">
              <strong class="sidenav-text">5</strong> new messages</a>
          </div>
        </div>
      </div>
    </li>
    <li class="sidenav-divider mt-0"></li>

    <% if user_signed_in? %>
      <li class="sidenav-item<%= current_page?(root_path) ? ' active' : '' %>">
        <%= link_to root_path, class: "sidenav-link" do %>
          <i class="sidenav-icon ion ion-ios-desktop"></i><div>Dashboard</div>
        <% end %>
      </li>
      <li class="sidenav-item<%= current_page?(contacts_path) ? ' active' : '' %>">
        <%= link_to contacts_path, class: "sidenav-link" do %>
          <i class="sidenav-icon ion ion-ios-contacts"></i><div>Contacts</div>
        <% end %>
      </li>
      
      <% if current_user.has_role?(:admin) %>
        <li class="sidenav-item<%= current_page?(agents_path) ? ' active' : '' %>">
          <%= link_to agents_path, class: "sidenav-link" do %>
            <i class="sidenav-icon ion ion-ios-contact"></i><div>Agents</div>
          <% end %>
        </li>
      <% end %>      
    
      <li class="sidenav-item">
        <%= link_to destroy_user_session_path, class: "sidenav-link", method: :delete do %>
          <i class="sidenav-icon ion ion-ios-power"></i><div>Sign Out</div>
        <% end %>
      </li>
    <% else %>
      <li class="sidenav-item">
        <%= link_to new_user_session_path, class: "sidenav-link" do %>
          <i class="sidenav-icon ion ion-ios-power"></i><div>Sign In</div>
        <% end %>
      </li>
    <% end %>

  </ul>
</div>
<!-- / Layout sidenav -->